<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Faker\Factory as Faker;

class SubmissionModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data dummy untuk submission_modules table
        $data = [
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->first()->id,
                'title' => 'Rapat Evaluasi Kinerja Kuartalan',
                'purpose' => 'Evaluasi kinerja kuartalan berdasarkan hasil keuangan dan pencapaian target penjualan.',
                'agenda' => "1. Presentasi hasil keuangan kuartal terakhir\n2. Diskusi tentang pencapaian target penjualan\n3. Perencanaan strategi pemasaran untuk kuartal mendatang\n4. Pengambilan keputusan tentang alokasi anggaran departemen",
                'date' => '2024-07-05',
                'time' => '09:00:00',
                'duration' => '3 jam',
                'type' => 'Tatap Muka',
                'location' => 'Gedung Utama',
                'supporting_document' => 'Laporan keuangan kuartal terakhir dan analisis pencapaian target penjualan.',
                'status' => 'Proses Persetujuan',
                'reason_cancelled' => '',
                'approved_at' => now(),
                'distributed_at' => now(),
                'implemented_at' => '2024-07-06 13:00:00',
                'provided_at' => '2024-07-05 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(1)->first()->id, // Ambil user kedua
                'title' => 'Rapat Strategi Pemasaran',
                'purpose' => 'Membahas strategi pemasaran untuk meningkatkan penjualan pada kuartal mendatang.',
                'agenda' => "1. Evaluasi strategi pemasaran saat ini\n2. Pembahasan ide-ide baru untuk kampanye pemasaran\n3. Penetapan anggaran untuk kampanye pemasaran",
                'date' => '2024-07-10',
                'time' => '10:00:00',
                'duration' => '2 jam',
                'type' => 'Daring',
                'location' => 'https://example.com/meeting1',
                'supporting_document' => 'https://example.com/meeting2',
                'postscript' => 'Pastikan semua peserta sudah terkoneksi ke Zoom sebelum rapat dimulai.',
                'status' => 'Sudah Disetujui',
                'reason_cancelled' => '',
                'approved_at' => '2024-07-08 09:00:00',
                'distributed_at' => '2024-07-09 08:00:00',
                'implemented_at' => '2024-07-10 12:00:00',
                'provided_at' => '2024-07-10 14:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(2)->first()->id,
                'title' => 'Rapat Pengalokasian Anggaran',
                'purpose' => 'Membahas pengalokasian anggaran departemen untuk proyek-proyek strategis.',
                'agenda' => "1. Evaluasi anggaran tahun ini\n2. Penyusunan anggaran untuk proyek-proyek baru\n3. Penetapan prioritas pengalokasian anggaran",
                'date' => '2024-07-15',
                'time' => '14:00:00',
                'duration' => '2.5 jam',
                'type' => 'Tatap Muka',
                'location' => 'Ruangan A3',
                'supporting_document' => 'Rincian anggaran departemen dan proposal-proposal proyek.',
                'postscript' => 'Pastikan semua peserta membawa rincian anggaran departemen masing-masing.',
                'status' => 'Undangan Didistribusikan',
                'reason_cancelled' => '',
                'approved_at' => '2024-07-13 10:00:00',
                'distributed_at' => '2024-07-14 09:00:00',
                'implemented_at' => null,
                'provided_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(3)->first()->id,
                'title' => 'Rapat Evaluasi Proyek X',
                'purpose' => 'Mengevaluasi kemajuan dan dampak proyek X terhadap tujuan perusahaan.',
                'agenda' => "1. Presentasi kemajuan proyek X\n2. Diskusi tentang masalah dan solusi yang dihadapi\n3. Penetapan langkah-langkah selanjutnya untuk memaksimalkan hasil proyek",
                'date' => '2024-07-20',
                'time' => '11:00:00',
                'duration' => '2 jam',
                'type' => 'Daring',
                'location' => 'Microsoft Teams',
                'supporting_document' => 'Laporan kemajuan proyek X dan analisis dampaknya terhadap operasional perusahaan.',
                'postscript' => 'Pastikan semua peserta sudah memiliki akses ke Microsoft Teams sebelum rapat dimulai.',
                'status' => 'Telah Dilaksanakan',
                'reason_cancelled' => '',
                'approved_at' => '2024-07-18 14:00:00',
                'distributed_at' => '2024-07-19 13:00:00',
                'implemented_at' => '2024-07-20 13:00:00',
                'provided_at' => '2024-07-20 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(4)->first()->id,
                'title' => 'Rapat Pembahasan Laporan Keuangan',
                'purpose' => 'Membahas hasil keuangan terkini dan menetapkan strategi keuangan ke depan.',
                'agenda' => "1. Presentasi hasil keuangan terbaru\n2. Diskusi tentang interpretasi laporan keuangan\n3. Penetapan langkah-langkah untuk memaksimalkan profitabilitas perusahaan",
                'date' => '2024-07-25',
                'time' => '15:00:00',
                'duration' => '2.5 jam',
                'type' => 'Tatap Muka',
                'location' => 'Ruang Rapat Utama',
                'supporting_document' => 'Laporan keuangan terbaru dan analisis kinerja keuangan perusahaan.',
                'postscript' => 'Pastikan semua peserta membawa salinan laporan keuangan yang akan dibahas.',
                'status' => 'Baru Ditambahkan',
                'reason_cancelled' => '',
                'approved_at' => '2024-07-23 11:00:00',
                'distributed_at' => '2024-07-24 10:00:00',
                'implemented_at' => '2024-07-25 17:00:00',
                'provided_at' => '2024-07-25 19:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(3)->first()->id, // Ambil user keenam
                'title' => 'Rapat Evaluasi Performa Penjualan',
                'purpose' => 'Mengevaluasi performa penjualan produk A dan B di pasar domestik.',
                'agenda' => "1. Presentasi hasil penjualan produk A\n2. Diskusi tentang strategi pemasaran produk B\n3. Perencanaan langkah-langkah peningkatan performa penjualan",
                'date' => '2024-07-30',
                'time' => '10:00:00',
                'duration' => '2 jam',
                'type' => 'Tatap Muka',
                'location' => 'Ruang Diskusi',
                'supporting_document' => 'Data penjualan produk A dan B serta analisis pasar domestik terbaru.',
                'postscript' => 'Pastikan semua peserta sudah mempersiapkan laporan penjualan masing-masing.',
                'status' => 'Dibatalkan',
                'reason_cancelled' => 'Bencana alam di daerah yang mempengaruhi sebagian besar peserta.',
                'approved_at' => now(),
                'distributed_at' => now(),
                'implemented_at' => null,
                'provided_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(1)->first()->id, // Ambil user ketujuh
                'title' => 'Rapat Evaluasi Proyek Y',
                'purpose' => 'Mengevaluasi proyek Y dan mengevaluasi kinerja tim proyek.',
                'agenda' => "1. Presentasi kemajuan proyek Y\n2. Diskusi tentang hambatan yang dihadapi\n3. Penetapan langkah-langkah untuk memastikan proyek selesai tepat waktu",
                'date' => '2024-08-05',
                'time' => '14:00:00',
                'duration' => '2.5 jam',
                'type' => 'Daring',
                'location' => 'Google Meet',
                'supporting_document' => 'Laporan kemajuan proyek Y dan analisis kinerja tim proyek.',
                'postscript' => 'Pastikan semua peserta sudah memiliki akses ke Google Meet sebelum rapat dimulai.',
                'status' => 'Sudah Disetujui',
                'reason_cancelled' => '',
                'approved_at' => '2024-08-03 10:00:00',
                'distributed_at' => '2024-08-04 09:00:00',
                'implemented_at' => '2024-08-05 16:00:00',
                'provided_at' => '2024-08-05 18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(2)->first()->id, // Ambil user kedelapan
                'title' => 'Rapat Evaluasi Performa IT',
                'purpose' => 'Mengevaluasi performa departemen IT dan merencanakan peningkatan infrastruktur IT.',
                'agenda' => "1. Presentasi hasil evaluasi sistem IT saat ini\n2. Diskusi tentang kebutuhan infrastruktur IT mendatang\n3. Penetapan anggaran untuk peningkatan sistem IT",
                'date' => '2024-08-10',
                'time' => '11:00:00',
                'duration' => '2 jam',
                'type' => 'Tatap Muka',
                'location' => 'Ruang IT',
                'supporting_document' => 'Laporan evaluasi sistem IT dan rekomendasi peningkatan infrastruktur.',
                'postscript' => 'Pastikan semua peserta telah mempersiapkan analisis kebutuhan IT masing-masing.',
                'status' => 'Undangan Didistribusikan',
                'reason_cancelled' => '',
                'approved_at' => '2024-08-08 14:00:00',
                'distributed_at' => '2024-08-09 13:00:00',
                'implemented_at' => null,
                'provided_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(3)->first()->id, // Ambil user kesembilan
                'title' => 'Rapat Evaluasi Layanan Pelanggan',
                'purpose' => 'Mengevaluasi kepuasan pelanggan dan merencanakan peningkatan layanan pelanggan.',
                'agenda' => "1. Presentasi hasil survei kepuasan pelanggan\n2. Diskusi tentang perbaikan layanan pelanggan\n3. Penetapan langkah-langkah untuk meningkatkan kepuasan pelanggan",
                'date' => '2024-08-15',
                'time' => '13:00:00',
                'duration' => '2.5 jam',
                'type' => 'Tatap Muka',
                'location' => 'Ruang Layanan Pelanggan',
                'supporting_document' => 'Hasil survei kepuasan pelanggan dan analisis tingkat kepuasan saat ini.',
                'postscript' => 'Pastikan semua peserta telah mempersiapkan rencana perbaikan layanan pelanggan.',
                'status' => 'Telah Dilaksanakan',
                'reason_cancelled' => '',
                'approved_at' => '2024-08-13 11:00:00',
                'distributed_at' => '2024-08-14 10:00:00',
                'implemented_at' => '2024-08-15 15:00:00',
                'provided_at' => '2024-08-15 17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => \Faker\Provider\Uuid::uuid(),
                'user_id' => DB::table('users')->skip(4)->first()->id, // Ambil user kesepuluh
                'title' => 'Rapat Evaluasi R&D',
                'purpose' => 'Mengevaluasi progres dan merencanakan inovasi di bidang R&D.',
                'agenda' => "1. Presentasi kemajuan proyek R&D\n2. Diskusi tentang peluang inovasi baru\n3. Penetapan anggaran untuk riset dan pengembangan",
                'date' => '2024-08-20',
                'time' => '09:00:00',
                'duration' => '3 jam',
                'type' => 'Daring',
                'location' => 'Microsoft Teams',
                'supporting_document' => 'Laporan kemajuan proyek R&D dan analisis potensi inovasi pasar.',
                'postscript' => 'Pastikan semua peserta sudah memiliki akses ke Microsoft Teams sebelum rapat dimulai.',
                'status' => 'Notula Tersedia',
                'reason_cancelled' => '',
                'approved_at' => '2024-08-18 09:00:00',
                'distributed_at' => '2024-08-19 08:00:00',
                'implemented_at' => '2024-08-20 12:00:00',
                'provided_at' => '2024-08-20 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data ke dalam tabel submission_modules
        foreach ($data as $item) {
            DB::table('submission_modules')->insert($item);
        }
    }
}
